---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fndmnts-ngnhr-app
  labels:
    name: fndmnts-ngnhr-app
spec:
  replicas: 1
  revisionHistoryLimit: 5
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: fndmnts-ngnhr-app
    spec:
      containers:
      - name: fndmnts-ngnhr-app
        image: fndmntsngnhr.azurecr.io/app:@env.CI_COMMIT_SHA@
        resources:
          limits:
            cpu: 2
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 128Mi
        readinessProbe:
          httpGet:
            path: /health
            port: 9090
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 9090
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 20
        ports:
        - containerPort: 8080
        - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: fndmnts-ngnhr-app
  labels:
    name: fndmnts-ngnhr-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    name: fndmnts-ngnhr-app